%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Deedy CV/Resume
% XeLaTeX Template
% Version 1.0 (5/5/2014)
%
% This template has been downloaded from:
% http://www.LaTeXTemplates.com
%
% Original author:
% Debarghya Das (http://www.debarghyadas.com)
% With extensive modifications by:
% Vel (vel@latextemplates.com)
%
% License:
% CC BY-NC-SA 3.0 (http://creativecommons.org/licenses/by-nc-sa/3.0/)
%
% Important notes:
% This template needs to be compiled with XeLaTeX.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\documentclass[letterpaper]{deedy-resume} % Use US Letter paper, change to a4paper for A4 

\begin{document}

%----------------------------------------------------------------------------------------
%	TITLE SECTION
%----------------------------------------------------------------------------------------

\lastupdated % Print the Last Updated text at the top right

\namesection{Nilanjana}{Lodh}{ % Your name
% \urlstyle{same}\url{http://debarghyadas.com} \\ % Your website, LinkedIn profile or other web address
\href{mailto:nilanjanalodh@google.com}{nilanjanalodh@google.com} | +91 redacted % Your contact information
}

%----------------------------------------------------------------------------------------
%	LEFT COLUMN
%----------------------------------------------------------------------------------------

\begin{minipage}[t]{0.33\textwidth} % The left column takes up 33% of the text width of the page

%------------------------------------------------
% Education
%------------------------------------------------

\section{Education} 

\sectionspace % Some whitespace after the section
\subsection{IIEST, Shibpur}
\sectionspace % Some whitespace after the section
\descript{B.Tech in Computer Science}
\location{Grad May 2018 | Howrah, India \\ GPA: \textbf{9.2 / 10.0} }

\sectionspace % Some whitespace after the section

\sectionspace % Some whitespace after the section

%------------------------------------------------

\subsection{Julien day school}
\sectionspace
\descript{Indian school certificate examinations}
\location{Grad. May 2018 | Kolkata, India \\
GPA: 96.5\% , \\
Top 1\% of 68,000 candidates 
}


\sectionspace % Some whitespace after the section
\sectionspace
\sectionspace
%------------------------------------------------
% Links
%------------------------------------------------

\section{Links} 
\sectionspace
Github:// \href{https://github.com/nilanjanalodh}{\bf nilanjanalodh} \\
LinkedIn:// \href{https://www.linkedin.com/in/nilanjana-lodh}{\bf nilanjana-lodh} \\


\sectionspace % Some whitespace after the section
\sectionspace
\sectionspace

%------------------------------------------------
% Skills
%------------------------------------------------

\section{Skills}

\sectionspace
\subsection{Programming}

\sectionspace
\location{Over 5000 lines:}
Java \textbullet{}  C \textbullet{} C++ \\
\sectionspace
\location{Over 1000 lines:}
MySQL \textbullet{} Python \textbullet{} Scala \\
\textbullet{} Javascript  \\


\sectionspace % Some whitespace after the section
\sectionspace
\sectionspace
%------------------------------------------------
% Coursework
%------------------------------------------------

\section{Coursework}


%------------------------------------------------

\subsection{Undergraduate}

Operating Systems \\
Algorithms \\
Database systems \\
Artificial Intelligence \\
Computational graphics \\

\sectionspace % Some whitespace after the section


%----------------------------------------------------------------------------------------

\end{minipage} % The end of the left column
\hfill
%
%----------------------------------------------------------------------------------------
%	RIGHT COLUMN
%----------------------------------------------------------------------------------------
%
\begin{minipage}[t]{0.66\textwidth} % The right column takes up 66% of the text width of the page

%------------------------------------------------
% Experience
%------------------------------------------------

\section{Experience}


\sectionspace % Some whitespace after the section

%------------------------------------------------

\runsubsection{Google}
\descript{| Software Engineer}

\location{July 2020 – Present | Bangalore, India}
\sectionspace % Some whitespace after the section
 Improve Google One - the one premium membership to get more out of Google.


\sectionspace % Some whitespace after the section
\sectionspace % Some whitespace after the section

%------------------------------------------------
\runsubsection{Media.net}
\descript{| Platform Engineer}

\location{July 2018 – July 2020 | Mumbai, India}
\sectionspace % Some whitespace after the section
Part of auto-optimization data engineering team.
\begin{itemize}
\item Set up and managed ETL pipelines for other teams with data rates of the order of million messages per minute.
\item Developed a prototype for automating resource recommendation for spark streaming jobs on the yarn cluster
\item Created a data pipeline management tool - which allowed dev team to offload data pipeline management to the operations team and drastically cut down the time to set up a pipeline
\end{itemize}

\sectionspace % Some whitespace after the section
\sectionspace % Some whitespace after the section



%------------------------------------------------

\runsubsection{Linux Foundation}
\descript{| Google Summer Of Code developer}

\location{May 2017 – Aug 2017 }
\begin{itemize}
\item Worked on the Common Printing Dialog Project which aims to fix the anomalies in user experience in print dialogs, and improve it.
\item  Developed DBus activatable CUPS, IPP Print Backends for Common Print Dialog
\item Developed Frontend and Backend Libraries for the dialog which enable the dialog frontend and backends to communicate over D-Bus
\end{itemize}

\sectionspace % Some whitespace after the section
\sectionspace % Some whitespace after the section

%------------------------------------------------

\runsubsection{Breezy}
\descript{| Software developer intern}
\location{Jun 2018 – July 2018 }
\begin{itemize}
\item Breezy is an enterprise cloud printing solutions company.
\item I developed the prototype for their Google cloud print connector service for relaying jobs over to the breezy server.
\end{itemize}

\sectionspace % Some whitespace after the section
\sectionspace % Some whitespace after the section
\sectionspace 


%-----------------------------------------------


%----------------------------------------------------------------------------------------

\end{minipage} % The end of the right column

%----------------------------------------------------------------------------------------
%	SECOND PAGE (EXAMPLE)
%----------------------------------------------------------------------------------------

%\newpage % Start a new page

%\begin{minipage}[t]{0.33\textwidth} % The left column takes up 33% of the text width of the page

%\section{Example Section}

%\end{minipage} % The end of the left column
%\hfill
%\begin{minipage}[t]{0.66\textwidth} % The right column takes up 66% of the text width of the page

%\section{Example Section 2}

%\end{minipage} % The end of the right column

%----------------------------------------------------------------------------------------

\end{document}
